# Generated by Django 4.0.5 on 2022-07-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Futbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=40)),
                ('integrantes', models.IntegerField()),
                ('email_representante', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(max_length=40)),
                ('id_torneo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TenisSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_participante', models.CharField(max_length=40)),
                ('email_tenista', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(max_length=40)),
                ('id_torneo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Volley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=40)),
                ('integrantes', models.IntegerField()),
                ('email_representante', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(max_length=40)),
                ('id_torneo', models.IntegerField()),
            ],
        ),
    ]
